-- niosv.vhd

-- Generated using ACDS version 25.1 1129

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity niosv is
	port (
		clk_clk : in std_logic := '0'  -- clk.clk
	);
end entity niosv;

architecture rtl of niosv is
	component altera_avalon_jtag_uart is
		generic (
			readBufferDepth            : integer := 64;
			readIRQThreshold           : integer := 8;
			useRegistersForReadBuffer  : boolean := false;
			useRegistersForWriteBuffer : boolean := false;
			writeBufferDepth           : integer := 64;
			writeIRQThreshold          : integer := 8;
			printingMethod             : boolean := false;
			FIFO_WIDTH                 : integer := 8;
			WR_WIDTHU                  : integer := 0;
			RD_WIDTHU                  : integer := 0;
			write_le                   : string  := """ON""";
			read_le                    : string  := """ON""";
			HEX_WRITE_DEPTH_STR        : integer := 64;
			HEX_READ_DEPTH_STR         : integer := 64;
			legacySignalAllow          : boolean := true
		);
		port (
			clk            : in  std_logic                     := 'X';             -- clk
			rst_n          : in  std_logic                     := 'X';             -- reset_n
			av_chipselect  : in  std_logic                     := 'X';             -- chipselect
			av_address     : in  std_logic                     := 'X';             -- address
			av_read_n      : in  std_logic                     := 'X';             -- read_n
			av_readdata    : out std_logic_vector(31 downto 0);                    -- readdata
			av_write_n     : in  std_logic                     := 'X';             -- write_n
			av_writedata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			av_waitrequest : out std_logic;                                        -- waitrequest
			av_irq         : out std_logic                                         -- irq
		);
	end component altera_avalon_jtag_uart;

	component niosv_My_NiosV is
		port (
			clk                          : in  std_logic                     := 'X';             -- clk
			reset_reset                  : in  std_logic                     := 'X';             -- reset
			platform_irq_rx_irq          : in  std_logic_vector(15 downto 0) := (others => 'X'); -- irq
			ndm_reset_in_reset           : in  std_logic                     := 'X';             -- reset
			timer_sw_agent_address       : in  std_logic_vector(5 downto 0)  := (others => 'X'); -- address
			timer_sw_agent_byteenable    : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			timer_sw_agent_read          : in  std_logic                     := 'X';             -- read
			timer_sw_agent_readdata      : out std_logic_vector(31 downto 0);                    -- readdata
			timer_sw_agent_write         : in  std_logic                     := 'X';             -- write
			timer_sw_agent_writedata     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			timer_sw_agent_waitrequest   : out std_logic;                                        -- waitrequest
			timer_sw_agent_readdatavalid : out std_logic;                                        -- readdatavalid
			instruction_manager_awaddr   : out std_logic_vector(31 downto 0);                    -- awaddr
			instruction_manager_awprot   : out std_logic_vector(2 downto 0);                     -- awprot
			instruction_manager_awvalid  : out std_logic;                                        -- awvalid
			instruction_manager_awready  : in  std_logic                     := 'X';             -- awready
			instruction_manager_wdata    : out std_logic_vector(31 downto 0);                    -- wdata
			instruction_manager_wstrb    : out std_logic_vector(3 downto 0);                     -- wstrb
			instruction_manager_wvalid   : out std_logic;                                        -- wvalid
			instruction_manager_wready   : in  std_logic                     := 'X';             -- wready
			instruction_manager_bresp    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- bresp
			instruction_manager_bvalid   : in  std_logic                     := 'X';             -- bvalid
			instruction_manager_bready   : out std_logic;                                        -- bready
			instruction_manager_araddr   : out std_logic_vector(31 downto 0);                    -- araddr
			instruction_manager_arprot   : out std_logic_vector(2 downto 0);                     -- arprot
			instruction_manager_arvalid  : out std_logic;                                        -- arvalid
			instruction_manager_arready  : in  std_logic                     := 'X';             -- arready
			instruction_manager_rdata    : in  std_logic_vector(31 downto 0) := (others => 'X'); -- rdata
			instruction_manager_rresp    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- rresp
			instruction_manager_rvalid   : in  std_logic                     := 'X';             -- rvalid
			instruction_manager_rready   : out std_logic;                                        -- rready
			data_manager_awaddr          : out std_logic_vector(31 downto 0);                    -- awaddr
			data_manager_awprot          : out std_logic_vector(2 downto 0);                     -- awprot
			data_manager_awvalid         : out std_logic;                                        -- awvalid
			data_manager_awready         : in  std_logic                     := 'X';             -- awready
			data_manager_wdata           : out std_logic_vector(31 downto 0);                    -- wdata
			data_manager_wstrb           : out std_logic_vector(3 downto 0);                     -- wstrb
			data_manager_wvalid          : out std_logic;                                        -- wvalid
			data_manager_wready          : in  std_logic                     := 'X';             -- wready
			data_manager_bresp           : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- bresp
			data_manager_bvalid          : in  std_logic                     := 'X';             -- bvalid
			data_manager_bready          : out std_logic;                                        -- bready
			data_manager_araddr          : out std_logic_vector(31 downto 0);                    -- araddr
			data_manager_arprot          : out std_logic_vector(2 downto 0);                     -- arprot
			data_manager_arvalid         : out std_logic;                                        -- arvalid
			data_manager_arready         : in  std_logic                     := 'X';             -- arready
			data_manager_rdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- rdata
			data_manager_rresp           : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- rresp
			data_manager_rvalid          : in  std_logic                     := 'X';             -- rvalid
			data_manager_rready          : out std_logic;                                        -- rready
			dm_agent_address             : in  std_logic_vector(15 downto 0) := (others => 'X'); -- address
			dm_agent_read                : in  std_logic                     := 'X';             -- read
			dm_agent_readdata            : out std_logic_vector(31 downto 0);                    -- readdata
			dm_agent_write               : in  std_logic                     := 'X';             -- write
			dm_agent_writedata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			dm_agent_waitrequest         : out std_logic;                                        -- waitrequest
			dm_agent_readdatavalid       : out std_logic;                                        -- readdatavalid
			dbg_reset_out_reset          : out std_logic                                         -- reset
		);
	end component niosv_My_NiosV;

	component niosv_SRAM is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			address    : in  std_logic_vector(14 downto 0) := (others => 'X'); -- address
			clken      : in  std_logic                     := 'X';             -- clken
			chipselect : in  std_logic                     := 'X';             -- chipselect
			write      : in  std_logic                     := 'X';             -- write
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			reset      : in  std_logic                     := 'X';             -- reset
			reset_req  : in  std_logic                     := 'X';             -- reset_req
			freeze     : in  std_logic                     := 'X'              -- freeze
		);
	end component niosv_SRAM;

	component niosv_mm_interconnect_0 is
		port (
			My_NiosV_data_manager_awaddr               : in  std_logic_vector(31 downto 0) := (others => 'X'); -- awaddr
			My_NiosV_data_manager_awprot               : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awprot
			My_NiosV_data_manager_awvalid              : in  std_logic                     := 'X';             -- awvalid
			My_NiosV_data_manager_awready              : out std_logic;                                        -- awready
			My_NiosV_data_manager_wdata                : in  std_logic_vector(31 downto 0) := (others => 'X'); -- wdata
			My_NiosV_data_manager_wstrb                : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wstrb
			My_NiosV_data_manager_wvalid               : in  std_logic                     := 'X';             -- wvalid
			My_NiosV_data_manager_wready               : out std_logic;                                        -- wready
			My_NiosV_data_manager_bresp                : out std_logic_vector(1 downto 0);                     -- bresp
			My_NiosV_data_manager_bvalid               : out std_logic;                                        -- bvalid
			My_NiosV_data_manager_bready               : in  std_logic                     := 'X';             -- bready
			My_NiosV_data_manager_araddr               : in  std_logic_vector(31 downto 0) := (others => 'X'); -- araddr
			My_NiosV_data_manager_arprot               : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arprot
			My_NiosV_data_manager_arvalid              : in  std_logic                     := 'X';             -- arvalid
			My_NiosV_data_manager_arready              : out std_logic;                                        -- arready
			My_NiosV_data_manager_rdata                : out std_logic_vector(31 downto 0);                    -- rdata
			My_NiosV_data_manager_rresp                : out std_logic_vector(1 downto 0);                     -- rresp
			My_NiosV_data_manager_rvalid               : out std_logic;                                        -- rvalid
			My_NiosV_data_manager_rready               : in  std_logic                     := 'X';             -- rready
			My_NiosV_instruction_manager_awaddr        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- awaddr
			My_NiosV_instruction_manager_awprot        : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awprot
			My_NiosV_instruction_manager_awvalid       : in  std_logic                     := 'X';             -- awvalid
			My_NiosV_instruction_manager_awready       : out std_logic;                                        -- awready
			My_NiosV_instruction_manager_wdata         : in  std_logic_vector(31 downto 0) := (others => 'X'); -- wdata
			My_NiosV_instruction_manager_wstrb         : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wstrb
			My_NiosV_instruction_manager_wvalid        : in  std_logic                     := 'X';             -- wvalid
			My_NiosV_instruction_manager_wready        : out std_logic;                                        -- wready
			My_NiosV_instruction_manager_bresp         : out std_logic_vector(1 downto 0);                     -- bresp
			My_NiosV_instruction_manager_bvalid        : out std_logic;                                        -- bvalid
			My_NiosV_instruction_manager_bready        : in  std_logic                     := 'X';             -- bready
			My_NiosV_instruction_manager_araddr        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- araddr
			My_NiosV_instruction_manager_arprot        : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arprot
			My_NiosV_instruction_manager_arvalid       : in  std_logic                     := 'X';             -- arvalid
			My_NiosV_instruction_manager_arready       : out std_logic;                                        -- arready
			My_NiosV_instruction_manager_rdata         : out std_logic_vector(31 downto 0);                    -- rdata
			My_NiosV_instruction_manager_rresp         : out std_logic_vector(1 downto 0);                     -- rresp
			My_NiosV_instruction_manager_rvalid        : out std_logic;                                        -- rvalid
			My_NiosV_instruction_manager_rready        : in  std_logic                     := 'X';             -- rready
			clk_0_clk_clk                              : in  std_logic                     := 'X';             -- clk
			My_NiosV_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			DEBUG_avalon_jtag_slave_address            : out std_logic_vector(0 downto 0);                     -- address
			DEBUG_avalon_jtag_slave_write              : out std_logic;                                        -- write
			DEBUG_avalon_jtag_slave_read               : out std_logic;                                        -- read
			DEBUG_avalon_jtag_slave_readdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			DEBUG_avalon_jtag_slave_writedata          : out std_logic_vector(31 downto 0);                    -- writedata
			DEBUG_avalon_jtag_slave_waitrequest        : in  std_logic                     := 'X';             -- waitrequest
			DEBUG_avalon_jtag_slave_chipselect         : out std_logic;                                        -- chipselect
			My_NiosV_dm_agent_address                  : out std_logic_vector(15 downto 0);                    -- address
			My_NiosV_dm_agent_write                    : out std_logic;                                        -- write
			My_NiosV_dm_agent_read                     : out std_logic;                                        -- read
			My_NiosV_dm_agent_readdata                 : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			My_NiosV_dm_agent_writedata                : out std_logic_vector(31 downto 0);                    -- writedata
			My_NiosV_dm_agent_readdatavalid            : in  std_logic                     := 'X';             -- readdatavalid
			My_NiosV_dm_agent_waitrequest              : in  std_logic                     := 'X';             -- waitrequest
			My_NiosV_timer_sw_agent_address            : out std_logic_vector(5 downto 0);                     -- address
			My_NiosV_timer_sw_agent_write              : out std_logic;                                        -- write
			My_NiosV_timer_sw_agent_read               : out std_logic;                                        -- read
			My_NiosV_timer_sw_agent_readdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			My_NiosV_timer_sw_agent_writedata          : out std_logic_vector(31 downto 0);                    -- writedata
			My_NiosV_timer_sw_agent_byteenable         : out std_logic_vector(3 downto 0);                     -- byteenable
			My_NiosV_timer_sw_agent_readdatavalid      : in  std_logic                     := 'X';             -- readdatavalid
			My_NiosV_timer_sw_agent_waitrequest        : in  std_logic                     := 'X';             -- waitrequest
			SRAM_s1_address                            : out std_logic_vector(14 downto 0);                    -- address
			SRAM_s1_write                              : out std_logic;                                        -- write
			SRAM_s1_readdata                           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			SRAM_s1_writedata                          : out std_logic_vector(31 downto 0);                    -- writedata
			SRAM_s1_byteenable                         : out std_logic_vector(3 downto 0);                     -- byteenable
			SRAM_s1_chipselect                         : out std_logic;                                        -- chipselect
			SRAM_s1_clken                              : out std_logic                                         -- clken
		);
	end component niosv_mm_interconnect_0;

	component niosv_irq_mapper is
		port (
			clk           : in  std_logic                     := 'X'; -- clk
			reset         : in  std_logic                     := 'X'; -- reset
			receiver0_irq : in  std_logic                     := 'X'; -- irq
			sender_irq    : out std_logic_vector(15 downto 0)         -- irq
		);
	end component niosv_irq_mapper;

	component altera_reset_controller is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_in1      : in  std_logic := 'X'; -- reset
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component altera_reset_controller;

	signal my_niosv_dbg_reset_out_reset                              : std_logic;                     -- My_NiosV:dbg_reset_out_reset -> rst_controller:reset_in0
	signal my_niosv_data_manager_awaddr                              : std_logic_vector(31 downto 0); -- My_NiosV:data_manager_awaddr -> mm_interconnect_0:My_NiosV_data_manager_awaddr
	signal my_niosv_data_manager_bresp                               : std_logic_vector(1 downto 0);  -- mm_interconnect_0:My_NiosV_data_manager_bresp -> My_NiosV:data_manager_bresp
	signal my_niosv_data_manager_arready                             : std_logic;                     -- mm_interconnect_0:My_NiosV_data_manager_arready -> My_NiosV:data_manager_arready
	signal my_niosv_data_manager_rdata                               : std_logic_vector(31 downto 0); -- mm_interconnect_0:My_NiosV_data_manager_rdata -> My_NiosV:data_manager_rdata
	signal my_niosv_data_manager_wstrb                               : std_logic_vector(3 downto 0);  -- My_NiosV:data_manager_wstrb -> mm_interconnect_0:My_NiosV_data_manager_wstrb
	signal my_niosv_data_manager_wready                              : std_logic;                     -- mm_interconnect_0:My_NiosV_data_manager_wready -> My_NiosV:data_manager_wready
	signal my_niosv_data_manager_awready                             : std_logic;                     -- mm_interconnect_0:My_NiosV_data_manager_awready -> My_NiosV:data_manager_awready
	signal my_niosv_data_manager_rready                              : std_logic;                     -- My_NiosV:data_manager_rready -> mm_interconnect_0:My_NiosV_data_manager_rready
	signal my_niosv_data_manager_bready                              : std_logic;                     -- My_NiosV:data_manager_bready -> mm_interconnect_0:My_NiosV_data_manager_bready
	signal my_niosv_data_manager_wvalid                              : std_logic;                     -- My_NiosV:data_manager_wvalid -> mm_interconnect_0:My_NiosV_data_manager_wvalid
	signal my_niosv_data_manager_araddr                              : std_logic_vector(31 downto 0); -- My_NiosV:data_manager_araddr -> mm_interconnect_0:My_NiosV_data_manager_araddr
	signal my_niosv_data_manager_arprot                              : std_logic_vector(2 downto 0);  -- My_NiosV:data_manager_arprot -> mm_interconnect_0:My_NiosV_data_manager_arprot
	signal my_niosv_data_manager_rresp                               : std_logic_vector(1 downto 0);  -- mm_interconnect_0:My_NiosV_data_manager_rresp -> My_NiosV:data_manager_rresp
	signal my_niosv_data_manager_awprot                              : std_logic_vector(2 downto 0);  -- My_NiosV:data_manager_awprot -> mm_interconnect_0:My_NiosV_data_manager_awprot
	signal my_niosv_data_manager_wdata                               : std_logic_vector(31 downto 0); -- My_NiosV:data_manager_wdata -> mm_interconnect_0:My_NiosV_data_manager_wdata
	signal my_niosv_data_manager_arvalid                             : std_logic;                     -- My_NiosV:data_manager_arvalid -> mm_interconnect_0:My_NiosV_data_manager_arvalid
	signal my_niosv_data_manager_bvalid                              : std_logic;                     -- mm_interconnect_0:My_NiosV_data_manager_bvalid -> My_NiosV:data_manager_bvalid
	signal my_niosv_data_manager_awvalid                             : std_logic;                     -- My_NiosV:data_manager_awvalid -> mm_interconnect_0:My_NiosV_data_manager_awvalid
	signal my_niosv_data_manager_rvalid                              : std_logic;                     -- mm_interconnect_0:My_NiosV_data_manager_rvalid -> My_NiosV:data_manager_rvalid
	signal my_niosv_instruction_manager_awaddr                       : std_logic_vector(31 downto 0); -- My_NiosV:instruction_manager_awaddr -> mm_interconnect_0:My_NiosV_instruction_manager_awaddr
	signal my_niosv_instruction_manager_bresp                        : std_logic_vector(1 downto 0);  -- mm_interconnect_0:My_NiosV_instruction_manager_bresp -> My_NiosV:instruction_manager_bresp
	signal my_niosv_instruction_manager_arready                      : std_logic;                     -- mm_interconnect_0:My_NiosV_instruction_manager_arready -> My_NiosV:instruction_manager_arready
	signal my_niosv_instruction_manager_rdata                        : std_logic_vector(31 downto 0); -- mm_interconnect_0:My_NiosV_instruction_manager_rdata -> My_NiosV:instruction_manager_rdata
	signal my_niosv_instruction_manager_wstrb                        : std_logic_vector(3 downto 0);  -- My_NiosV:instruction_manager_wstrb -> mm_interconnect_0:My_NiosV_instruction_manager_wstrb
	signal my_niosv_instruction_manager_wready                       : std_logic;                     -- mm_interconnect_0:My_NiosV_instruction_manager_wready -> My_NiosV:instruction_manager_wready
	signal my_niosv_instruction_manager_awready                      : std_logic;                     -- mm_interconnect_0:My_NiosV_instruction_manager_awready -> My_NiosV:instruction_manager_awready
	signal my_niosv_instruction_manager_rready                       : std_logic;                     -- My_NiosV:instruction_manager_rready -> mm_interconnect_0:My_NiosV_instruction_manager_rready
	signal my_niosv_instruction_manager_bready                       : std_logic;                     -- My_NiosV:instruction_manager_bready -> mm_interconnect_0:My_NiosV_instruction_manager_bready
	signal my_niosv_instruction_manager_wvalid                       : std_logic;                     -- My_NiosV:instruction_manager_wvalid -> mm_interconnect_0:My_NiosV_instruction_manager_wvalid
	signal my_niosv_instruction_manager_araddr                       : std_logic_vector(31 downto 0); -- My_NiosV:instruction_manager_araddr -> mm_interconnect_0:My_NiosV_instruction_manager_araddr
	signal my_niosv_instruction_manager_arprot                       : std_logic_vector(2 downto 0);  -- My_NiosV:instruction_manager_arprot -> mm_interconnect_0:My_NiosV_instruction_manager_arprot
	signal my_niosv_instruction_manager_rresp                        : std_logic_vector(1 downto 0);  -- mm_interconnect_0:My_NiosV_instruction_manager_rresp -> My_NiosV:instruction_manager_rresp
	signal my_niosv_instruction_manager_awprot                       : std_logic_vector(2 downto 0);  -- My_NiosV:instruction_manager_awprot -> mm_interconnect_0:My_NiosV_instruction_manager_awprot
	signal my_niosv_instruction_manager_wdata                        : std_logic_vector(31 downto 0); -- My_NiosV:instruction_manager_wdata -> mm_interconnect_0:My_NiosV_instruction_manager_wdata
	signal my_niosv_instruction_manager_arvalid                      : std_logic;                     -- My_NiosV:instruction_manager_arvalid -> mm_interconnect_0:My_NiosV_instruction_manager_arvalid
	signal my_niosv_instruction_manager_bvalid                       : std_logic;                     -- mm_interconnect_0:My_NiosV_instruction_manager_bvalid -> My_NiosV:instruction_manager_bvalid
	signal my_niosv_instruction_manager_awvalid                      : std_logic;                     -- My_NiosV:instruction_manager_awvalid -> mm_interconnect_0:My_NiosV_instruction_manager_awvalid
	signal my_niosv_instruction_manager_rvalid                       : std_logic;                     -- mm_interconnect_0:My_NiosV_instruction_manager_rvalid -> My_NiosV:instruction_manager_rvalid
	signal mm_interconnect_0_debug_avalon_jtag_slave_chipselect      : std_logic;                     -- mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	signal mm_interconnect_0_debug_avalon_jtag_slave_readdata        : std_logic_vector(31 downto 0); -- DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	signal mm_interconnect_0_debug_avalon_jtag_slave_waitrequest     : std_logic;                     -- DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	signal mm_interconnect_0_debug_avalon_jtag_slave_address         : std_logic_vector(0 downto 0);  -- mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	signal mm_interconnect_0_debug_avalon_jtag_slave_read            : std_logic;                     -- mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> mm_interconnect_0_debug_avalon_jtag_slave_read:in
	signal mm_interconnect_0_debug_avalon_jtag_slave_write           : std_logic;                     -- mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> mm_interconnect_0_debug_avalon_jtag_slave_write:in
	signal mm_interconnect_0_debug_avalon_jtag_slave_writedata       : std_logic_vector(31 downto 0); -- mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	signal mm_interconnect_0_my_niosv_dm_agent_readdata              : std_logic_vector(31 downto 0); -- My_NiosV:dm_agent_readdata -> mm_interconnect_0:My_NiosV_dm_agent_readdata
	signal mm_interconnect_0_my_niosv_dm_agent_waitrequest           : std_logic;                     -- My_NiosV:dm_agent_waitrequest -> mm_interconnect_0:My_NiosV_dm_agent_waitrequest
	signal mm_interconnect_0_my_niosv_dm_agent_address               : std_logic_vector(15 downto 0); -- mm_interconnect_0:My_NiosV_dm_agent_address -> My_NiosV:dm_agent_address
	signal mm_interconnect_0_my_niosv_dm_agent_read                  : std_logic;                     -- mm_interconnect_0:My_NiosV_dm_agent_read -> My_NiosV:dm_agent_read
	signal mm_interconnect_0_my_niosv_dm_agent_readdatavalid         : std_logic;                     -- My_NiosV:dm_agent_readdatavalid -> mm_interconnect_0:My_NiosV_dm_agent_readdatavalid
	signal mm_interconnect_0_my_niosv_dm_agent_write                 : std_logic;                     -- mm_interconnect_0:My_NiosV_dm_agent_write -> My_NiosV:dm_agent_write
	signal mm_interconnect_0_my_niosv_dm_agent_writedata             : std_logic_vector(31 downto 0); -- mm_interconnect_0:My_NiosV_dm_agent_writedata -> My_NiosV:dm_agent_writedata
	signal mm_interconnect_0_sram_s1_chipselect                      : std_logic;                     -- mm_interconnect_0:SRAM_s1_chipselect -> SRAM:chipselect
	signal mm_interconnect_0_sram_s1_readdata                        : std_logic_vector(31 downto 0); -- SRAM:readdata -> mm_interconnect_0:SRAM_s1_readdata
	signal mm_interconnect_0_sram_s1_address                         : std_logic_vector(14 downto 0); -- mm_interconnect_0:SRAM_s1_address -> SRAM:address
	signal mm_interconnect_0_sram_s1_byteenable                      : std_logic_vector(3 downto 0);  -- mm_interconnect_0:SRAM_s1_byteenable -> SRAM:byteenable
	signal mm_interconnect_0_sram_s1_write                           : std_logic;                     -- mm_interconnect_0:SRAM_s1_write -> SRAM:write
	signal mm_interconnect_0_sram_s1_writedata                       : std_logic_vector(31 downto 0); -- mm_interconnect_0:SRAM_s1_writedata -> SRAM:writedata
	signal mm_interconnect_0_sram_s1_clken                           : std_logic;                     -- mm_interconnect_0:SRAM_s1_clken -> SRAM:clken
	signal mm_interconnect_0_my_niosv_timer_sw_agent_readdata        : std_logic_vector(31 downto 0); -- My_NiosV:timer_sw_agent_readdata -> mm_interconnect_0:My_NiosV_timer_sw_agent_readdata
	signal mm_interconnect_0_my_niosv_timer_sw_agent_waitrequest     : std_logic;                     -- My_NiosV:timer_sw_agent_waitrequest -> mm_interconnect_0:My_NiosV_timer_sw_agent_waitrequest
	signal mm_interconnect_0_my_niosv_timer_sw_agent_address         : std_logic_vector(5 downto 0);  -- mm_interconnect_0:My_NiosV_timer_sw_agent_address -> My_NiosV:timer_sw_agent_address
	signal mm_interconnect_0_my_niosv_timer_sw_agent_read            : std_logic;                     -- mm_interconnect_0:My_NiosV_timer_sw_agent_read -> My_NiosV:timer_sw_agent_read
	signal mm_interconnect_0_my_niosv_timer_sw_agent_byteenable      : std_logic_vector(3 downto 0);  -- mm_interconnect_0:My_NiosV_timer_sw_agent_byteenable -> My_NiosV:timer_sw_agent_byteenable
	signal mm_interconnect_0_my_niosv_timer_sw_agent_readdatavalid   : std_logic;                     -- My_NiosV:timer_sw_agent_readdatavalid -> mm_interconnect_0:My_NiosV_timer_sw_agent_readdatavalid
	signal mm_interconnect_0_my_niosv_timer_sw_agent_write           : std_logic;                     -- mm_interconnect_0:My_NiosV_timer_sw_agent_write -> My_NiosV:timer_sw_agent_write
	signal mm_interconnect_0_my_niosv_timer_sw_agent_writedata       : std_logic_vector(31 downto 0); -- mm_interconnect_0:My_NiosV_timer_sw_agent_writedata -> My_NiosV:timer_sw_agent_writedata
	signal irq_mapper_receiver0_irq                                  : std_logic;                     -- DEBUG:av_irq -> irq_mapper:receiver0_irq
	signal my_niosv_platform_irq_rx_irq                              : std_logic_vector(15 downto 0); -- irq_mapper:sender_irq -> My_NiosV:platform_irq_rx_irq
	signal rst_controller_reset_out_reset                            : std_logic;                     -- rst_controller:reset_out -> [My_NiosV:ndm_reset_in_reset, My_NiosV:reset_reset, SRAM:reset, irq_mapper:reset, mm_interconnect_0:My_NiosV_reset_reset_bridge_in_reset_reset, rst_controller_reset_out_reset:in, rst_translator:in_reset]
	signal rst_controller_reset_out_reset_req                        : std_logic;                     -- rst_controller:reset_req -> [SRAM:reset_req, rst_translator:reset_req_in]
	signal mm_interconnect_0_debug_avalon_jtag_slave_read_ports_inv  : std_logic;                     -- mm_interconnect_0_debug_avalon_jtag_slave_read:inv -> DEBUG:av_read_n
	signal mm_interconnect_0_debug_avalon_jtag_slave_write_ports_inv : std_logic;                     -- mm_interconnect_0_debug_avalon_jtag_slave_write:inv -> DEBUG:av_write_n
	signal rst_controller_reset_out_reset_ports_inv                  : std_logic;                     -- rst_controller_reset_out_reset:inv -> DEBUG:rst_n

begin

	debug : component altera_avalon_jtag_uart
		generic map (
			readBufferDepth            => 64,
			readIRQThreshold           => 8,
			useRegistersForReadBuffer  => false,
			useRegistersForWriteBuffer => false,
			writeBufferDepth           => 64,
			writeIRQThreshold          => 8,
			printingMethod             => false,
			FIFO_WIDTH                 => 8,
			WR_WIDTHU                  => 6,
			RD_WIDTHU                  => 6,
			write_le                   => "ON",
			read_le                    => "ON",
			HEX_WRITE_DEPTH_STR        => 64,
			HEX_READ_DEPTH_STR         => 64,
			legacySignalAllow          => false
		)
		port map (
			clk            => clk_clk,                                                   --               clk.clk
			rst_n          => rst_controller_reset_out_reset_ports_inv,                  --             reset.reset_n
			av_chipselect  => mm_interconnect_0_debug_avalon_jtag_slave_chipselect,      -- avalon_jtag_slave.chipselect
			av_address     => mm_interconnect_0_debug_avalon_jtag_slave_address(0),      --                  .address
			av_read_n      => mm_interconnect_0_debug_avalon_jtag_slave_read_ports_inv,  --                  .read_n
			av_readdata    => mm_interconnect_0_debug_avalon_jtag_slave_readdata,        --                  .readdata
			av_write_n     => mm_interconnect_0_debug_avalon_jtag_slave_write_ports_inv, --                  .write_n
			av_writedata   => mm_interconnect_0_debug_avalon_jtag_slave_writedata,       --                  .writedata
			av_waitrequest => mm_interconnect_0_debug_avalon_jtag_slave_waitrequest,     --                  .waitrequest
			av_irq         => irq_mapper_receiver0_irq                                   --               irq.irq
		);

	my_niosv : component niosv_My_NiosV
		port map (
			clk                          => clk_clk,                                                 --                 clk.clk
			reset_reset                  => rst_controller_reset_out_reset,                          --               reset.reset
			platform_irq_rx_irq          => my_niosv_platform_irq_rx_irq,                            --     platform_irq_rx.irq
			ndm_reset_in_reset           => rst_controller_reset_out_reset,                          --        ndm_reset_in.reset
			timer_sw_agent_address       => mm_interconnect_0_my_niosv_timer_sw_agent_address,       --      timer_sw_agent.address
			timer_sw_agent_byteenable    => mm_interconnect_0_my_niosv_timer_sw_agent_byteenable,    --                    .byteenable
			timer_sw_agent_read          => mm_interconnect_0_my_niosv_timer_sw_agent_read,          --                    .read
			timer_sw_agent_readdata      => mm_interconnect_0_my_niosv_timer_sw_agent_readdata,      --                    .readdata
			timer_sw_agent_write         => mm_interconnect_0_my_niosv_timer_sw_agent_write,         --                    .write
			timer_sw_agent_writedata     => mm_interconnect_0_my_niosv_timer_sw_agent_writedata,     --                    .writedata
			timer_sw_agent_waitrequest   => mm_interconnect_0_my_niosv_timer_sw_agent_waitrequest,   --                    .waitrequest
			timer_sw_agent_readdatavalid => mm_interconnect_0_my_niosv_timer_sw_agent_readdatavalid, --                    .readdatavalid
			instruction_manager_awaddr   => my_niosv_instruction_manager_awaddr,                     -- instruction_manager.awaddr
			instruction_manager_awprot   => my_niosv_instruction_manager_awprot,                     --                    .awprot
			instruction_manager_awvalid  => my_niosv_instruction_manager_awvalid,                    --                    .awvalid
			instruction_manager_awready  => my_niosv_instruction_manager_awready,                    --                    .awready
			instruction_manager_wdata    => my_niosv_instruction_manager_wdata,                      --                    .wdata
			instruction_manager_wstrb    => my_niosv_instruction_manager_wstrb,                      --                    .wstrb
			instruction_manager_wvalid   => my_niosv_instruction_manager_wvalid,                     --                    .wvalid
			instruction_manager_wready   => my_niosv_instruction_manager_wready,                     --                    .wready
			instruction_manager_bresp    => my_niosv_instruction_manager_bresp,                      --                    .bresp
			instruction_manager_bvalid   => my_niosv_instruction_manager_bvalid,                     --                    .bvalid
			instruction_manager_bready   => my_niosv_instruction_manager_bready,                     --                    .bready
			instruction_manager_araddr   => my_niosv_instruction_manager_araddr,                     --                    .araddr
			instruction_manager_arprot   => my_niosv_instruction_manager_arprot,                     --                    .arprot
			instruction_manager_arvalid  => my_niosv_instruction_manager_arvalid,                    --                    .arvalid
			instruction_manager_arready  => my_niosv_instruction_manager_arready,                    --                    .arready
			instruction_manager_rdata    => my_niosv_instruction_manager_rdata,                      --                    .rdata
			instruction_manager_rresp    => my_niosv_instruction_manager_rresp,                      --                    .rresp
			instruction_manager_rvalid   => my_niosv_instruction_manager_rvalid,                     --                    .rvalid
			instruction_manager_rready   => my_niosv_instruction_manager_rready,                     --                    .rready
			data_manager_awaddr          => my_niosv_data_manager_awaddr,                            --        data_manager.awaddr
			data_manager_awprot          => my_niosv_data_manager_awprot,                            --                    .awprot
			data_manager_awvalid         => my_niosv_data_manager_awvalid,                           --                    .awvalid
			data_manager_awready         => my_niosv_data_manager_awready,                           --                    .awready
			data_manager_wdata           => my_niosv_data_manager_wdata,                             --                    .wdata
			data_manager_wstrb           => my_niosv_data_manager_wstrb,                             --                    .wstrb
			data_manager_wvalid          => my_niosv_data_manager_wvalid,                            --                    .wvalid
			data_manager_wready          => my_niosv_data_manager_wready,                            --                    .wready
			data_manager_bresp           => my_niosv_data_manager_bresp,                             --                    .bresp
			data_manager_bvalid          => my_niosv_data_manager_bvalid,                            --                    .bvalid
			data_manager_bready          => my_niosv_data_manager_bready,                            --                    .bready
			data_manager_araddr          => my_niosv_data_manager_araddr,                            --                    .araddr
			data_manager_arprot          => my_niosv_data_manager_arprot,                            --                    .arprot
			data_manager_arvalid         => my_niosv_data_manager_arvalid,                           --                    .arvalid
			data_manager_arready         => my_niosv_data_manager_arready,                           --                    .arready
			data_manager_rdata           => my_niosv_data_manager_rdata,                             --                    .rdata
			data_manager_rresp           => my_niosv_data_manager_rresp,                             --                    .rresp
			data_manager_rvalid          => my_niosv_data_manager_rvalid,                            --                    .rvalid
			data_manager_rready          => my_niosv_data_manager_rready,                            --                    .rready
			dm_agent_address             => mm_interconnect_0_my_niosv_dm_agent_address,             --            dm_agent.address
			dm_agent_read                => mm_interconnect_0_my_niosv_dm_agent_read,                --                    .read
			dm_agent_readdata            => mm_interconnect_0_my_niosv_dm_agent_readdata,            --                    .readdata
			dm_agent_write               => mm_interconnect_0_my_niosv_dm_agent_write,               --                    .write
			dm_agent_writedata           => mm_interconnect_0_my_niosv_dm_agent_writedata,           --                    .writedata
			dm_agent_waitrequest         => mm_interconnect_0_my_niosv_dm_agent_waitrequest,         --                    .waitrequest
			dm_agent_readdatavalid       => mm_interconnect_0_my_niosv_dm_agent_readdatavalid,       --                    .readdatavalid
			dbg_reset_out_reset          => my_niosv_dbg_reset_out_reset                             --       dbg_reset_out.reset
		);

	sram : component niosv_SRAM
		port map (
			clk        => clk_clk,                              --   clk1.clk
			address    => mm_interconnect_0_sram_s1_address,    --     s1.address
			clken      => mm_interconnect_0_sram_s1_clken,      --       .clken
			chipselect => mm_interconnect_0_sram_s1_chipselect, --       .chipselect
			write      => mm_interconnect_0_sram_s1_write,      --       .write
			readdata   => mm_interconnect_0_sram_s1_readdata,   --       .readdata
			writedata  => mm_interconnect_0_sram_s1_writedata,  --       .writedata
			byteenable => mm_interconnect_0_sram_s1_byteenable, --       .byteenable
			reset      => rst_controller_reset_out_reset,       -- reset1.reset
			reset_req  => rst_controller_reset_out_reset_req,   --       .reset_req
			freeze     => '0'                                   -- (terminated)
		);

	mm_interconnect_0 : component niosv_mm_interconnect_0
		port map (
			My_NiosV_data_manager_awaddr               => my_niosv_data_manager_awaddr,                            --                My_NiosV_data_manager.awaddr
			My_NiosV_data_manager_awprot               => my_niosv_data_manager_awprot,                            --                                     .awprot
			My_NiosV_data_manager_awvalid              => my_niosv_data_manager_awvalid,                           --                                     .awvalid
			My_NiosV_data_manager_awready              => my_niosv_data_manager_awready,                           --                                     .awready
			My_NiosV_data_manager_wdata                => my_niosv_data_manager_wdata,                             --                                     .wdata
			My_NiosV_data_manager_wstrb                => my_niosv_data_manager_wstrb,                             --                                     .wstrb
			My_NiosV_data_manager_wvalid               => my_niosv_data_manager_wvalid,                            --                                     .wvalid
			My_NiosV_data_manager_wready               => my_niosv_data_manager_wready,                            --                                     .wready
			My_NiosV_data_manager_bresp                => my_niosv_data_manager_bresp,                             --                                     .bresp
			My_NiosV_data_manager_bvalid               => my_niosv_data_manager_bvalid,                            --                                     .bvalid
			My_NiosV_data_manager_bready               => my_niosv_data_manager_bready,                            --                                     .bready
			My_NiosV_data_manager_araddr               => my_niosv_data_manager_araddr,                            --                                     .araddr
			My_NiosV_data_manager_arprot               => my_niosv_data_manager_arprot,                            --                                     .arprot
			My_NiosV_data_manager_arvalid              => my_niosv_data_manager_arvalid,                           --                                     .arvalid
			My_NiosV_data_manager_arready              => my_niosv_data_manager_arready,                           --                                     .arready
			My_NiosV_data_manager_rdata                => my_niosv_data_manager_rdata,                             --                                     .rdata
			My_NiosV_data_manager_rresp                => my_niosv_data_manager_rresp,                             --                                     .rresp
			My_NiosV_data_manager_rvalid               => my_niosv_data_manager_rvalid,                            --                                     .rvalid
			My_NiosV_data_manager_rready               => my_niosv_data_manager_rready,                            --                                     .rready
			My_NiosV_instruction_manager_awaddr        => my_niosv_instruction_manager_awaddr,                     --         My_NiosV_instruction_manager.awaddr
			My_NiosV_instruction_manager_awprot        => my_niosv_instruction_manager_awprot,                     --                                     .awprot
			My_NiosV_instruction_manager_awvalid       => my_niosv_instruction_manager_awvalid,                    --                                     .awvalid
			My_NiosV_instruction_manager_awready       => my_niosv_instruction_manager_awready,                    --                                     .awready
			My_NiosV_instruction_manager_wdata         => my_niosv_instruction_manager_wdata,                      --                                     .wdata
			My_NiosV_instruction_manager_wstrb         => my_niosv_instruction_manager_wstrb,                      --                                     .wstrb
			My_NiosV_instruction_manager_wvalid        => my_niosv_instruction_manager_wvalid,                     --                                     .wvalid
			My_NiosV_instruction_manager_wready        => my_niosv_instruction_manager_wready,                     --                                     .wready
			My_NiosV_instruction_manager_bresp         => my_niosv_instruction_manager_bresp,                      --                                     .bresp
			My_NiosV_instruction_manager_bvalid        => my_niosv_instruction_manager_bvalid,                     --                                     .bvalid
			My_NiosV_instruction_manager_bready        => my_niosv_instruction_manager_bready,                     --                                     .bready
			My_NiosV_instruction_manager_araddr        => my_niosv_instruction_manager_araddr,                     --                                     .araddr
			My_NiosV_instruction_manager_arprot        => my_niosv_instruction_manager_arprot,                     --                                     .arprot
			My_NiosV_instruction_manager_arvalid       => my_niosv_instruction_manager_arvalid,                    --                                     .arvalid
			My_NiosV_instruction_manager_arready       => my_niosv_instruction_manager_arready,                    --                                     .arready
			My_NiosV_instruction_manager_rdata         => my_niosv_instruction_manager_rdata,                      --                                     .rdata
			My_NiosV_instruction_manager_rresp         => my_niosv_instruction_manager_rresp,                      --                                     .rresp
			My_NiosV_instruction_manager_rvalid        => my_niosv_instruction_manager_rvalid,                     --                                     .rvalid
			My_NiosV_instruction_manager_rready        => my_niosv_instruction_manager_rready,                     --                                     .rready
			clk_0_clk_clk                              => clk_clk,                                                 --                            clk_0_clk.clk
			My_NiosV_reset_reset_bridge_in_reset_reset => rst_controller_reset_out_reset,                          -- My_NiosV_reset_reset_bridge_in_reset.reset
			DEBUG_avalon_jtag_slave_address            => mm_interconnect_0_debug_avalon_jtag_slave_address,       --              DEBUG_avalon_jtag_slave.address
			DEBUG_avalon_jtag_slave_write              => mm_interconnect_0_debug_avalon_jtag_slave_write,         --                                     .write
			DEBUG_avalon_jtag_slave_read               => mm_interconnect_0_debug_avalon_jtag_slave_read,          --                                     .read
			DEBUG_avalon_jtag_slave_readdata           => mm_interconnect_0_debug_avalon_jtag_slave_readdata,      --                                     .readdata
			DEBUG_avalon_jtag_slave_writedata          => mm_interconnect_0_debug_avalon_jtag_slave_writedata,     --                                     .writedata
			DEBUG_avalon_jtag_slave_waitrequest        => mm_interconnect_0_debug_avalon_jtag_slave_waitrequest,   --                                     .waitrequest
			DEBUG_avalon_jtag_slave_chipselect         => mm_interconnect_0_debug_avalon_jtag_slave_chipselect,    --                                     .chipselect
			My_NiosV_dm_agent_address                  => mm_interconnect_0_my_niosv_dm_agent_address,             --                    My_NiosV_dm_agent.address
			My_NiosV_dm_agent_write                    => mm_interconnect_0_my_niosv_dm_agent_write,               --                                     .write
			My_NiosV_dm_agent_read                     => mm_interconnect_0_my_niosv_dm_agent_read,                --                                     .read
			My_NiosV_dm_agent_readdata                 => mm_interconnect_0_my_niosv_dm_agent_readdata,            --                                     .readdata
			My_NiosV_dm_agent_writedata                => mm_interconnect_0_my_niosv_dm_agent_writedata,           --                                     .writedata
			My_NiosV_dm_agent_readdatavalid            => mm_interconnect_0_my_niosv_dm_agent_readdatavalid,       --                                     .readdatavalid
			My_NiosV_dm_agent_waitrequest              => mm_interconnect_0_my_niosv_dm_agent_waitrequest,         --                                     .waitrequest
			My_NiosV_timer_sw_agent_address            => mm_interconnect_0_my_niosv_timer_sw_agent_address,       --              My_NiosV_timer_sw_agent.address
			My_NiosV_timer_sw_agent_write              => mm_interconnect_0_my_niosv_timer_sw_agent_write,         --                                     .write
			My_NiosV_timer_sw_agent_read               => mm_interconnect_0_my_niosv_timer_sw_agent_read,          --                                     .read
			My_NiosV_timer_sw_agent_readdata           => mm_interconnect_0_my_niosv_timer_sw_agent_readdata,      --                                     .readdata
			My_NiosV_timer_sw_agent_writedata          => mm_interconnect_0_my_niosv_timer_sw_agent_writedata,     --                                     .writedata
			My_NiosV_timer_sw_agent_byteenable         => mm_interconnect_0_my_niosv_timer_sw_agent_byteenable,    --                                     .byteenable
			My_NiosV_timer_sw_agent_readdatavalid      => mm_interconnect_0_my_niosv_timer_sw_agent_readdatavalid, --                                     .readdatavalid
			My_NiosV_timer_sw_agent_waitrequest        => mm_interconnect_0_my_niosv_timer_sw_agent_waitrequest,   --                                     .waitrequest
			SRAM_s1_address                            => mm_interconnect_0_sram_s1_address,                       --                              SRAM_s1.address
			SRAM_s1_write                              => mm_interconnect_0_sram_s1_write,                         --                                     .write
			SRAM_s1_readdata                           => mm_interconnect_0_sram_s1_readdata,                      --                                     .readdata
			SRAM_s1_writedata                          => mm_interconnect_0_sram_s1_writedata,                     --                                     .writedata
			SRAM_s1_byteenable                         => mm_interconnect_0_sram_s1_byteenable,                    --                                     .byteenable
			SRAM_s1_chipselect                         => mm_interconnect_0_sram_s1_chipselect,                    --                                     .chipselect
			SRAM_s1_clken                              => mm_interconnect_0_sram_s1_clken                          --                                     .clken
		);

	irq_mapper : component niosv_irq_mapper
		port map (
			clk           => clk_clk,                        --       clk.clk
			reset         => rst_controller_reset_out_reset, -- clk_reset.reset
			receiver0_irq => irq_mapper_receiver0_irq,       -- receiver0.irq
			sender_irq    => my_niosv_platform_irq_rx_irq    --    sender.irq
		);

	rst_controller : component altera_reset_controller
		generic map (
			NUM_RESET_INPUTS          => 1,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 1,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => my_niosv_dbg_reset_out_reset,       -- reset_in0.reset
			clk            => clk_clk,                            --       clk.clk
			reset_out      => rst_controller_reset_out_reset,     -- reset_out.reset
			reset_req      => rst_controller_reset_out_reset_req, --          .reset_req
			reset_req_in0  => '0',                                -- (terminated)
			reset_in1      => '0',                                -- (terminated)
			reset_req_in1  => '0',                                -- (terminated)
			reset_in2      => '0',                                -- (terminated)
			reset_req_in2  => '0',                                -- (terminated)
			reset_in3      => '0',                                -- (terminated)
			reset_req_in3  => '0',                                -- (terminated)
			reset_in4      => '0',                                -- (terminated)
			reset_req_in4  => '0',                                -- (terminated)
			reset_in5      => '0',                                -- (terminated)
			reset_req_in5  => '0',                                -- (terminated)
			reset_in6      => '0',                                -- (terminated)
			reset_req_in6  => '0',                                -- (terminated)
			reset_in7      => '0',                                -- (terminated)
			reset_req_in7  => '0',                                -- (terminated)
			reset_in8      => '0',                                -- (terminated)
			reset_req_in8  => '0',                                -- (terminated)
			reset_in9      => '0',                                -- (terminated)
			reset_req_in9  => '0',                                -- (terminated)
			reset_in10     => '0',                                -- (terminated)
			reset_req_in10 => '0',                                -- (terminated)
			reset_in11     => '0',                                -- (terminated)
			reset_req_in11 => '0',                                -- (terminated)
			reset_in12     => '0',                                -- (terminated)
			reset_req_in12 => '0',                                -- (terminated)
			reset_in13     => '0',                                -- (terminated)
			reset_req_in13 => '0',                                -- (terminated)
			reset_in14     => '0',                                -- (terminated)
			reset_req_in14 => '0',                                -- (terminated)
			reset_in15     => '0',                                -- (terminated)
			reset_req_in15 => '0'                                 -- (terminated)
		);

	mm_interconnect_0_debug_avalon_jtag_slave_read_ports_inv <= not mm_interconnect_0_debug_avalon_jtag_slave_read;

	mm_interconnect_0_debug_avalon_jtag_slave_write_ports_inv <= not mm_interconnect_0_debug_avalon_jtag_slave_write;

	rst_controller_reset_out_reset_ports_inv <= not rst_controller_reset_out_reset;

end architecture rtl; -- of niosv
